config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  resources :products
  resources :imports, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/csv_builder.rb
class CsvBuilder < ProductDataBuilder
  def build(csv_row)
    data = csv_row.to_h.symbolize_keys
    formatter.format(data)
  end
end

app/models/csv_importer.rb
require "csv"

class CsvImporter < FileImporter
  def import
    CSV.foreach(filepath, headers: true) do |row|
      built_data = builder.build(row)
      Product.create(built_data)
    end
  end
end

app/models/file_importer.rb
class FileImporter
  attr_reader :filepath, :builder

  def initialize(filepath, builder)
    @filepath = filepath
    @builder = builder
  end

  def import
    raise "Must overwrite method"
  end
end

app/models/product.rb
require "csv"

class Product < ApplicationRecord
  validates :name, presence: true
end

app/models/product_data_builder.rb
class ProductDataBuilder
  attr_reader :formatter

  def initialize(formatter)
    @formatter = formatter
  end

  def build
    raise "Must override method"
  end
end

app/models/product_data_formatter.rb
class ProductDataFormatter
  def format(data)
    data[:active] = data[:active] == "true"
    data[:release_date] = parse_release_date(data[:release_date])
    data[:value] = parse_value(data[:value])
    data
  end

  private

  def parse_release_date(input)
    if input.is_a?(Float)
      Time.zone.parse(input.to_i.to_s)
    elsif input.is_a?(DateTime)
      input
    else
      Time.zone.parse(input)
    end
  end

  def parse_value(input)
    input.to_s.gsub(/^\$/, "").to_i
  end
end

app/models/product_data_importer.rb
class ProductDataImporter
  attr_reader :filepath, :formatter

  def initialize(filepath, formatter)
    @filepath = filepath
    @formatter = formatter
  end

  def import
    case File.extname(filepath)
    when ".csv"
      builder = CsvBuilder.new(formatter)
      CsvImporter.new(filepath, builder).import
    when ".xlsx"
      builder = XlsxBuilder.new(formatter)
      XlsxImporter.new(filepath, builder).import
    else
      raise "Unknown file type"
    end
  end
end

app/models/xlsx_builder.rb
class XlsxBuilder < ProductDataBuilder
  HEADERS = %w[name author release_date value version active].freeze

  def build(xlsx_row)
    cells = xlsx_row.cells.map(&:value)
    data = HEADERS.zip(cells).to_h.symbolize_keys
    formatter.format(data)
  end
end

app/models/xlsx_importer.rb
class XlsxImporter < FileImporter
  def import
    Xlsx.foreach(filepath) do |row|
      built_data = builder.build(row)
      Product.create(built_data)
    end
  end

  private

  class Xlsx
    def self.foreach(filepath)
      workbook = RubyXL::Parser.parse(filepath)
      worksheet = workbook.worksheets.first
      worksheet.each_with_index do |row, idx|
        if idx == 0
          next
        end
        yield(row)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def create
    ProductDataImporter.import(params[:file].path)
    redirect_to products_path, notice: "Succesfully imported"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    products = Product.all

    render locals: { products: products }
  end

  def new
    product = Product.new

    render locals: { product: product }
  end

  def create
    product = Product.new(product_params)

    if product.save
      flash[:success] = "Product created"
      redirect_to products_path
    else
      flash[:error] = product.errors.full_messages
      render new, locals: { product: product }
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    flash[:success] = "Product destroyed"
    redirect_to products_path
  end

  def edit
    product = Product.find(params[:id])

    if product
      render locals: { product: product }
    else
      flash[:error] = "Product not found"
      redirect_to products_path
    end
  end

  def update
    product = Product.find(params[:id])

    if product.update(product_params)
      flash[:success] = "Product updated"
      redirect_to products_path
    else
      flash[:error] = product.errors.full_messages
      redirect_to products_path
    end
  end

  def show
    product = Product.find(params[:id])

    render locals: { product: product }
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :release_date,
      :version,
      :value,
      :author,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SprinklesOfFunctionalProgrammingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for product do |f| %>
  <%= f.input :name %>
  <%= f.input :release_date, as: :date %>
  <%= f.input :version  %>
  <%= f.input :value %>
  <%= f.input :author %>
  <%= f.submit %>
<% end %>

app/views/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.author %></td>
  <td><%= product.version %></td>
  <td><%= product.release_date %></td>
  <td><%= product.value %></td>
  <td><%= link_to "Show", product_url(product) %></td>
</tr>

app/views/products/edit.html.erb
Edit Product Form

<%= render "form", product: product %>

app/views/products/index.html.erb
<h1>Products Index</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Version</th>
      <th>Release Date</th>
      <th>Value</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
  <% products.each do |product| %>
    <%= render "product", product: product %>
  <% end %>
  </tbody>
</table>

<%= link_to "Create a New Product", new_product_path %>

<%= form_tag imports_path, multipart: true do %>
  <label for="file">upload csv</label>
  <%= file_field_tag "file" %>
  <%= submit_tag "Upload File" %>
<% end %>

app/views/products/new.html.erb
<h1>New Product Form</h1>

<%= render "form", product: product %>

app/views/products/show.html.erb
<h2><%= product.name %></h2>

<p>Author: <%= product.author %></p>
<p>Version: <%= product.version %></p>
<p>Released On: <%= product.release_date %></p>
<p>Value: <%= product.value %></p>

<br/>

<%= link_to "Back", products_url %>
<%= link_to "Edit", edit_product_url(product) %>
<%= button_to "Delete", product_url(product), method: :delete, confirm: "Are you sure?" %>